### Array

In [4]:
from array import *
arr=array('i',[2,3,4,5])
print(arr)
print(arr[0])

array('i', [2, 3, 4, 5])
2


In [5]:
arr.insert(4,6)
arr

array('i', [2, 3, 4, 5, 6])

In [6]:
arr.remove(4)
arr

array('i', [2, 3, 5, 6])

In [7]:
arr.index(5)

2

In [8]:
arr[0] = 1
arr

array('i', [1, 3, 5, 6])

In [9]:
def min_max(arr):
    maximum = arr[0]
    minimum = arr[0]
    for i in arr:
        if i > maximum:
            maximum = i

        if i < minimum:
            minimum = i
    print("Minimum:", minimum, "Maximum:", maximum)
min_max(arr)

Minimum: 1 Maximum: 6


### Average

In [18]:
import array as arr
x = arr.array('i',[3,5,6,2,7,8,4,5])
type(x)
x_sum = sum(x)
print("sum:", x_sum)
length = len(x)
average = x_sum/length
print("Average:",average)

sum: 40
Average: 5.0


### Reverse

In [20]:
a = arr.array('i',[2,3,4,5,6,7])
print(a[::-1])

array('i', [7, 6, 5, 4, 3, 2])


In [30]:
a = arr.array('i',[2,3,4,5,6,7])
new_arr=[]
for i in range(len(a)-1,-1,-1):
    new_arr.append(a[i])

print(new_arr)

[7, 6, 5, 4, 3, 2]


### distninct remove

In [47]:
n = arr.array('i',[2,2,4,5,7,8,4,3])
def dist_remove(n): 
    f_arr = []
    for i in n:        
            if i not in f_arr:
                f_arr.append(i)
    return f_arr

dist_remove(n)

[2, 4, 5, 7, 8, 3]

In [53]:
import numpy as np
x = np.array([2,2,4,5,78,8,4,3])
x = np.array(list(set(x)))
print(x)


[ 2  3  4  5  8 78]


In [59]:
x = np.array([2,2,4,5,78,8,4,3])
def remove_dist(x):
    x = np.array(list(set(x)))
    return x

remove_dist(x)

array([ 2,  3,  4,  5,  8, 78])

### find the element  

In [1]:
import array

def find_index():
    a = array.array('i', [2, 3, 4, 5, 6, 7])
    n = int(input("Enter the element: "))
    try:
        index = a.index(n)
        print(f"The index of {n} is {index}")
    except ValueError:
        print(-1)

find_index()


Enter the element:  6


The index of 6 is 4


### sum of array elements

In [4]:
import numpy as np 
x = np.array([2,3,4,5,7])
sum = 0    
for i in x :
        sum +=i

print(sum)

21


### Array intersection

In [24]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 2,3,5,3])
a2 = np.array([2, 3, 4, 31,3,5,5,3,3])
a3 = []

for x in a1:
    for j in a2:
        if x == j and x not in a3:
            a3.append(x)

a3 = np.array(a3)
print(a3)


[2 3 4 5]


### Rotate an array

In [28]:
def rotate_right(d,arr):
    n = len(arr)
    d = d%n
    arr =arr[d:] + arr[d:]
    return arr

rotate_right(2,[1,2,3,4,5])

[1, 2, 3, 4, 5]